export const initialVaules = {
  fname: "Jhon",
  lname: "Doe",
  email: "jhonDoe32@gmail.com",
  dob: "10-11-1998",
  job: "Developer",
  gender: "",
  bio: "",
  storedPassword: "12345",
};
export const column = [
  {
    Header: "Name of users",
    accessor: "name",
  },

  {
    Header: "Occupation",
    accessor: "occupation",
  },
  {
    Header: "Last Active",
    accessor: "last active",
  },
  {
    Header: "Status",
    accessor: "status",
  },
  {
    Header: "Action",
    accessor: "action",
  },
];
export const TableData = [
  {
    id: 1,
    name: "Obediah Reek",
    email: "oreek0@smugmug.com",
    occupation: "Human Resources Manager",
    "last active": "6/13/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 2,
    name: "Stanislaus Bambridge",
    email: "sbambridge1@feedburner.com",
    occupation: "GIS Technical Architect",
    "last active": "10/16/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 3,
    name: "Jayne Matresse",
    email: "jmatresse2@canalblog.com",
    occupation: "Research Assistant III",
    "last active": "7/5/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 4,
    name: "Domingo Sprowles",
    email: "dsprowles3@4shared.com",
    occupation: "Senior Financial Analyst",
    "last active": "11/15/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 5,
    name: "Billy Hawthorne",
    email: "bhawthorne4@sitemeter.com",
    occupation: "Account Coordinator",
    "last active": "6/26/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 6,
    name: "Norton De Clairmont",
    email: "nde5@imgur.com",
    occupation: "Nurse Practicioner",
    "last active": "6/12/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 7,
    name: "Diahann Nevin",
    email: "dnevin6@blinklist.com",
    occupation: "Research Nurse",
    "last active": "10/11/2023",
    status: "Active",
    action: null,
  },
  {
    id: 8,
    name: "Allie Casley",
    email: "acasley7@constantcontact.com",
    occupation: "Senior Cost Accountant",
    "last active": "8/10/2023",
    status: "Active",
    action: null,
  },
  {
    id: 9,
    name: "Krissie Grevile",
    email: "kgrevile8@mozilla.com",
    occupation: "Product Engineer",
    "last active": "4/8/2024",
    status: "Active",
    action: null,
  },
  {
    id: 10,
    name: "Cazzie Birch",
    email: "cbirch9@shutterfly.com",
    occupation: "Account Representative IV",
    "last active": "6/29/2023",
    status: "Active",
    action: null,
  },
  {
    id: 11,
    name: "Tonya Kubicki",
    email: "tkubickia@cbsnews.com",
    occupation: "Help Desk Operator",
    "last active": "4/27/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 12,
    name: "Angelique Rodell",
    email: "arodellb@sun.com",
    occupation: "Financial Analyst",
    "last active": "2/10/2024",
    status: "Active",
    action: null,
  },
  {
    id: 13,
    name: "Chaunce Carruth",
    email: "ccarruthc@microsoft.com",
    occupation: "Sales Associate",
    "last active": "3/9/2024",
    status: "Active",
    action: null,
  },
  {
    id: 14,
    name: "Kelsey Vell",
    email: "kvelld@auda.org.au",
    occupation: "Web Developer I",
    "last active": "11/30/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 15,
    name: "Ginger Beauman",
    email: "gbeaumane@ocn.ne.jp",
    occupation: "Programmer Analyst III",
    "last active": "2/2/2024",
    status: "Active",
    action: null,
  },
  {
    id: 16,
    name: "Hyman Flay",
    email: "hflayf@home.pl",
    occupation: "Design Engineer",
    "last active": "7/14/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 17,
    name: "Quintilla Du Pre",
    email: "qdug@1688.com",
    occupation: "Software Test Engineer IV",
    "last active": "4/14/2024",
    status: "Active",
    action: null,
  },
  {
    id: 18,
    name: "Ellene Breddy",
    email: "ebreddyh@chronoengine.com",
    occupation: "Sales Associate",
    "last active": "6/15/2023",
    status: "Active",
    action: null,
  },
  {
    id: 19,
    name: "Niko Lacrouts",
    email: "nlacroutsi@weebly.com",
    occupation: "VP Product Management",
    "last active": "4/18/2024",
    status: "Active",
    action: null,
  },
  {
    id: 20,
    name: "Gradey Morfield",
    email: "gmorfieldj@zimbio.com",
    occupation: "VP Marketing",
    "last active": "4/6/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 21,
    name: "Elfrieda Joselovitch",
    email: "ejoselovitchk@berkeley.edu",
    occupation: "Tax Accountant",
    "last active": "8/8/2023",
    status: "Active",
    action: null,
  },
  {
    id: 22,
    name: "Aprilette Curman",
    email: "acurmanl@ask.com",
    occupation: "Senior Financial Analyst",
    "last active": "1/15/2024",
    status: "Active",
    action: null,
  },
  {
    id: 23,
    name: "Whit Denholm",
    email: "wdenholmm@last.fm",
    occupation: "Research Nurse",
    "last active": "11/10/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 24,
    name: "Jillane Shapero",
    email: "jshaperon@sfgate.com",
    occupation: "Sales Representative",
    "last active": "6/22/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 25,
    name: "Gabriellia Kittles",
    email: "gkittleso@webmd.com",
    occupation: "Structural Analysis Engineer",
    "last active": "3/3/2024",
    status: "Active",
    action: null,
  },
  {
    id: 26,
    name: "Irwinn Bellini",
    email: "ibellinip@mtv.com",
    occupation: "Analyst Programmer",
    "last active": "3/9/2024",
    status: "Active",
    action: null,
  },
  {
    id: 27,
    name: "Latashia Ickovic",
    email: "lickovicq@meetup.com",
    occupation: "Nurse Practicioner",
    "last active": "4/5/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 28,
    name: "Henka Durram",
    email: "hdurramr@hc360.com",
    occupation: "Accountant III",
    "last active": "8/3/2023",
    status: "Active",
    action: null,
  },
  {
    id: 29,
    name: "Mandy Pepin",
    email: "mpepins@pbs.org",
    occupation: "Software Test Engineer I",
    "last active": "12/31/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 30,
    name: "Viki Billings",
    email: "vbillingst@meetup.com",
    occupation: "Professor",
    "last active": "2/23/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 31,
    name: "Reeva Claxson",
    email: "rclaxsonu@amazon.de",
    occupation: "Environmental Tech",
    "last active": "11/11/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 32,
    name: "Vanna Mougeot",
    email: "vmougeotv@icq.com",
    occupation: "Engineer I",
    "last active": "1/9/2024",
    status: "Active",
    action: null,
  },
  {
    id: 33,
    name: "Jeri Parlot",
    email: "jparlotw@boston.com",
    occupation: "Senior Developer",
    "last active": "2/13/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 34,
    name: "Eddie Guerreru",
    email: "eguerrerux@aboutads.info",
    occupation: "Nuclear Power Engineer",
    "last active": "5/3/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 35,
    name: "Melva Carme",
    email: "mcarmey@fastcompany.com",
    occupation: "Data Coordinator",
    "last active": "1/13/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 36,
    name: "Zacharie Scherer",
    email: "zschererz@goo.ne.jp",
    occupation: "Media Manager III",
    "last active": "6/4/2023",
    status: "Active",
    action: null,
  },
  {
    id: 37,
    name: "Judd Colthard",
    email: "jcolthard10@desdev.cn",
    occupation: "Nuclear Power Engineer",
    "last active": "12/2/2023",
    status: "Active",
    action: null,
  },
  {
    id: 38,
    name: "Rollo Cokayne",
    email: "rcokayne11@cmu.edu",
    occupation: "Automation Specialist II",
    "last active": "12/9/2023",
    status: "Active",
    action: null,
  },
  {
    id: 39,
    name: "Joeann Canadas",
    email: "jcanadas12@netscape.com",
    occupation: "Actuary",
    "last active": "11/16/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 40,
    name: "Dell Marien",
    email: "dmarien13@google.com.au",
    occupation: "Physical Therapy Assistant",
    "last active": "12/5/2023",
    status: "Active",
    action: null,
  },
  {
    id: 41,
    name: "Marcos Holme",
    email: "mholme14@cloudflare.com",
    occupation: "Analyst Programmer",
    "last active": "9/4/2023",
    status: "Active",
    action: null,
  },
  {
    id: 42,
    name: "Naoma Summerell",
    email: "nsummerell15@netlog.com",
    occupation: "Senior Sales Associate",
    "last active": "9/2/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 43,
    name: "Spike Minogue",
    email: "sminogue16@github.io",
    occupation: "Sales Representative",
    "last active": "4/30/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 44,
    name: "Erminie Doerren",
    email: "edoerren17@twitter.com",
    occupation: "Automation Specialist I",
    "last active": "4/23/2024",
    status: "Active",
    action: null,
  },
  {
    id: 45,
    name: "Darice Dingwall",
    email: "ddingwall18@google.com.hk",
    occupation: "Administrative Assistant I",
    "last active": "4/7/2024",
    status: "Active",
    action: null,
  },
  {
    id: 46,
    name: "Fidela Babst",
    email: "fbabst19@soundcloud.com",
    occupation: "Programmer II",
    "last active": "11/7/2023",
    status: "Active",
    action: null,
  },
  {
    id: 47,
    name: "Aggie Moss",
    email: "amoss1a@go.com",
    occupation: "Automation Specialist II",
    "last active": "1/25/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 48,
    name: "Pincus Chetwind",
    email: "pchetwind1b@phpbb.com",
    occupation: "Speech Pathologist",
    "last active": "10/17/2023",
    status: "Active",
    action: null,
  },
  {
    id: 49,
    name: "Brendan Mattheis",
    email: "bmattheis1c@issuu.com",
    occupation: "Programmer III",
    "last active": "7/21/2023",
    status: "Active",
    action: null,
  },
  {
    id: 50,
    name: "Troy Searle",
    email: "tsearle1d@hc360.com",
    occupation: "Cost Accountant",
    "last active": "4/21/2024",
    status: "Active",
    action: null,
  },
  {
    id: 51,
    name: "Gabriell Joseph",
    email: "gjoseph1e@newyorker.com",
    occupation: "Biostatistician I",
    "last active": "11/13/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 52,
    name: "Ileana Danniel",
    email: "idanniel1f@yelp.com",
    occupation: "Community Outreach Specialist",
    "last active": "7/30/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 53,
    name: "Ram Derye-Barrett",
    email: "rderyebarrett1g@yolasite.com",
    occupation: "Information Systems Manager",
    "last active": "4/12/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 54,
    name: "Talbert Bicknell",
    email: "tbicknell1h@independent.co.uk",
    occupation: "Civil Engineer",
    "last active": "5/14/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 55,
    name: "Franky Speck",
    email: "fspeck1i@etsy.com",
    occupation: "Chief Design Engineer",
    "last active": "5/5/2024",
    status: "Active",
    action: null,
  },
  {
    id: 56,
    name: "Ruggiero Hugland",
    email: "rhugland1j@marketwatch.com",
    occupation: "Registered Nurse",
    "last active": "9/13/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 57,
    name: "Nikolaos Blant",
    email: "nblant1k@imgur.com",
    occupation: "Biostatistician I",
    "last active": "4/24/2024",
    status: "Active",
    action: null,
  },
  {
    id: 58,
    name: "Adena Boeck",
    email: "aboeck1l@mapy.cz",
    occupation: "VP Product Management",
    "last active": "5/1/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 59,
    name: "Cynthie Avon",
    email: "cavon1m@ucla.edu",
    occupation: "Human Resources Manager",
    "last active": "4/15/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 60,
    name: "Gale Laugier",
    email: "glaugier1n@java.com",
    occupation: "Teacher",
    "last active": "1/12/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 61,
    name: "Benedetta Pudsey",
    email: "bpudsey1o@thetimes.co.uk",
    occupation: "Senior Financial Analyst",
    "last active": "8/16/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 62,
    name: "Ciel Tubbles",
    email: "ctubbles1p@noaa.gov",
    occupation: "Dental Hygienist",
    "last active": "6/11/2023",
    status: "Active",
    action: null,
  },
  {
    id: 63,
    name: "Sally Calven",
    email: "scalven1q@google.ru",
    occupation: "Help Desk Technician",
    "last active": "6/2/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 64,
    name: "Courtney Allsupp",
    email: "callsupp1r@behance.net",
    occupation: "Staff Scientist",
    "last active": "8/30/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 65,
    name: "Cynthea Glader",
    email: "cglader1s@examiner.com",
    occupation: "Assistant Media Planner",
    "last active": "3/2/2024",
    status: "Active",
    action: null,
  },
  {
    id: 66,
    name: "Clemente Dupree",
    email: "cdupree1t@nasa.gov",
    occupation: "Financial Analyst",
    "last active": "1/17/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 67,
    name: "Millicent Meader",
    email: "mmeader1u@unc.edu",
    occupation: "Teacher",
    "last active": "1/31/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 68,
    name: "Kendall Marcos",
    email: "kmarcos1v@is.gd",
    occupation: "Geologist IV",
    "last active": "1/8/2024",
    status: "Active",
    action: null,
  },
  {
    id: 69,
    name: "Sella Sparhawk",
    email: "ssparhawk1w@nsw.gov.au",
    occupation: "Operator",
    "last active": "12/18/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 70,
    name: "Emylee Moorhead",
    email: "emoorhead1x@github.io",
    occupation: "Registered Nurse",
    "last active": "5/22/2024",
    status: "Active",
    action: null,
  },
  {
    id: 71,
    name: "Chryste Pirt",
    email: "cpirt1y@linkedin.com",
    occupation: "Staff Scientist",
    "last active": "12/23/2023",
    status: "Active",
    action: null,
  },
  {
    id: 72,
    name: "Kelvin Chattock",
    email: "kchattock1z@home.pl",
    occupation: "Teacher",
    "last active": "10/18/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 73,
    name: "Artemas Ormiston",
    email: "aormiston20@hugedomains.com",
    occupation: "Web Designer II",
    "last active": "11/26/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 74,
    name: "Katharina Cattermull",
    email: "kcattermull21@tripod.com",
    occupation: "Research Assistant II",
    "last active": "4/3/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 75,
    name: "Rivkah Edds",
    email: "redds22@baidu.com",
    occupation: "Nurse",
    "last active": "8/30/2023",
    status: "Active",
    action: null,
  },
  {
    id: 76,
    name: "Karissa Plail",
    email: "kplail23@mozilla.org",
    occupation: "Structural Analysis Engineer",
    "last active": "4/21/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 77,
    name: "Ulrike Margeram",
    email: "umargeram24@latimes.com",
    occupation: "Administrative Officer",
    "last active": "6/13/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 78,
    name: "Merna Leynton",
    email: "mleynton25@wikipedia.org",
    occupation: "Software Test Engineer II",
    "last active": "8/9/2023",
    status: "Active",
    action: null,
  },
  {
    id: 79,
    name: "Darcey Belchem",
    email: "dbelchem26@wikispaces.com",
    occupation: "Speech Pathologist",
    "last active": "11/23/2023",
    status: "Active",
    action: null,
  },
  {
    id: 80,
    name: "Haslett Radband",
    email: "hradband27@google.ca",
    occupation: "Web Developer III",
    "last active": "10/24/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 81,
    name: "Langston Siflet",
    email: "lsiflet28@time.com",
    occupation: "Director of Sales",
    "last active": "3/28/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 82,
    name: "Amalita Carnegie",
    email: "acarnegie29@ovh.net",
    occupation: "Junior Executive",
    "last active": "8/10/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 83,
    name: "Theodora Sallan",
    email: "tsallan2a@canalblog.com",
    occupation: "Assistant Media Planner",
    "last active": "11/3/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 84,
    name: "Celinda Kaine",
    email: "ckaine2b@smh.com.au",
    occupation: "Media Manager I",
    "last active": "4/22/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 85,
    name: "Ogden Siddaley",
    email: "osiddaley2c@google.ca",
    occupation: "Sales Associate",
    "last active": "11/7/2023",
    status: "Active",
    action: null,
  },
  {
    id: 86,
    name: "Jacquelyn Sambath",
    email: "jsambath2d@cloudflare.com",
    occupation: "Professor",
    "last active": "2/14/2024",
    status: "Active",
    action: null,
  },
  {
    id: 87,
    name: "Marcy Bebis",
    email: "mbebis2e@typepad.com",
    occupation: "Internal Auditor",
    "last active": "4/30/2024",
    status: "Active",
    action: null,
  },
  {
    id: 88,
    name: "Wilton Beedom",
    email: "wbeedom2f@diigo.com",
    occupation: "Nurse",
    "last active": "4/8/2024",
    status: "Active",
    action: null,
  },
  {
    id: 89,
    name: "Amanda Dallaghan",
    email: "adallaghan2g@pen.io",
    occupation: "Clinical Specialist",
    "last active": "4/27/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 90,
    name: "Nara Cronkshaw",
    email: "ncronkshaw2h@lycos.com",
    occupation: "Database Administrator I",
    "last active": "8/21/2023",
    status: "Active",
    action: null,
  },
  {
    id: 91,
    name: "Johanna Assante",
    email: "jassante2i@uol.com.br",
    occupation: "Programmer Analyst I",
    "last active": "7/10/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 92,
    name: "Clair MacTrustam",
    email: "cmactrustam2j@google.fr",
    occupation: "Account Executive",
    "last active": "11/17/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 93,
    name: "Marcile Willoughey",
    email: "mwilloughey2k@toplist.cz",
    occupation: "Compensation Analyst",
    "last active": "9/10/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 94,
    name: "Daveen Pennock",
    email: "dpennock2l@gnu.org",
    occupation: "VP Marketing",
    "last active": "5/4/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 95,
    name: "Karleen Moakson",
    email: "kmoakson2m@t-online.de",
    occupation: "Nurse Practicioner",
    "last active": "11/17/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 96,
    name: "Curt Danelutti",
    email: "cdanelutti2n@odnoklassniki.ru",
    occupation: "Recruiter",
    "last active": "9/2/2023",
    status: "Not Active",
    action: null,
  },
  {
    id: 97,
    name: "Dora McConnachie",
    email: "dmcconnachie2o@symantec.com",
    occupation: "Web Developer II",
    "last active": "11/20/2023",
    status: "Active",
    action: null,
  },
  {
    id: 98,
    name: "Bertina Wand",
    email: "bwand2p@illinois.edu",
    occupation: "Design Engineer",
    "last active": "8/8/2023",
    status: "Active",
    action: null,
  },
  {
    id: 99,
    name: "Katalin Tefft",
    email: "ktefft2q@ezinearticles.com",
    occupation: "Biostatistician IV",
    "last active": "2/6/2024",
    status: "Not Active",
    action: null,
  },
  {
    id: 100,
    name: "Harman Chelsom",
    email: "hchelsom2r@cam.ac.uk",
    occupation: "Physical Therapy Assistant",
    "last active": "9/27/2023",
    status: "Not Active",
    action: null,
  },
];
